rm(list = ls())
graphics.off
setwd("C:\\University_Stuff\\Time series\\Assignment")
library("zoo")
library('vars')
source('C:\\University_Stuff\\Time series\\ac.R')
dat <- read.csv(file = "jh-alsi40.csv", sep = ";", stringsAsFactors=FALSE)
dat$DATE <- as.Date(dat$DATE, format = "%d-%b-%y")
closingpricetemp <- diff(log(dat$CLOSE), lag = 1)
returns <- zoo(closingpricetemp, order.by = dat$DATE)
pastreturns <- lag(returns, lag = 1)
acf(coredata(returns))
df1 <- ur.df(returns, type = "none", selectlags = "AIC")
df2 <- ur.df(returns, type = "trend", selectlags = "AIC")
df3 <- ur.df(returns, type = "drift", selectlags = "AIC")
summary(df1)
summary(df2)
summary(df3)
plot(returns, xlab = "Date", col = "blue")
